// app/layout.js
import './globals.css';
import type { Metadata } from 'next';
import Script from 'next/script';
import { Geist, Geist_Mono } from 'next/font/google';
import StoreProvider from './StoreProvider';
import Header from '@/components/Header';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { SidebarInterceptor } from '@/components/SidebarInterceptor';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Whisker',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* 1. Load the Webchat bundle as early as possible */}
        <Script
          src="https://media.twiliocdn.com/sdk/js/webchat-v3/releases/3.3.0/webchat.min.js"
          integrity="sha256-ydLLXnNrb26iFUvKAHsYt9atwfzz0LNcgBmo0NmD5Uk="
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
        
        
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider defaultOpen={false}>
          <StoreProvider>
            <SidebarInset className="flex flex-col">
              <SidebarInterceptor />
              <Header />

              {/* 2. Render the chat widget’s root node */}
              <div id="twilio-webchat-widget-root"></div>

              {/* 3. Initialize Webchat on the client */}
              <Script id="twilio-webchat-init" strategy="afterInteractive">
  {`
    Twilio.initWebchat({
      deploymentKey: "${process.env.NEXT_PUBLIC_TWILIO_DEPLOYMENT_KEY}"
    });
  `}
</Script>


              {children}
            </SidebarInset>
          </StoreProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
