// app/layout.js
import "./globals.css";
import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import StoreProvider from "./StoreProvider";
import Header from "@/components/Header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { SidebarInterceptor } from "@/components/SidebarInterceptor";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Whisker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Load Twilio Webchat bundle */}
        <Script
          src="https://media.twiliocdn.com/sdk/js/webchat-v3/releases/3.3.0/webchat.min.js"
          integrity="sha256-ydLLXnNrb26iFUvKAHsYt9atwfzz0LNcgBmo0NmD5Uk="
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Webchat mounts directly under <body> so it can float */}
        <div id="twilio-webchat-widget-root"></div>
        <ToastContainer />

        <SidebarProvider defaultOpen={false}>
          <StoreProvider>
            <SidebarInset className="flex flex-col">
              <SidebarInterceptor />
              <Header />
              {children}
            </SidebarInset>
          </StoreProvider>
        </SidebarProvider>

        {/* Init Webchat */}
        <Script id="twilio-webchat-init" strategy="afterInteractive">
          {`
            Twilio.initWebchat({
              deploymentKey: "${process.env.NEXT_PUBLIC_TWILIO_DEPLOYMENT_KEY}"
            });
          `}
        </Script>
      </body>
    </html>
  );
}
